SELECT CITY, LENGTH(CITY) AS `length` FROM STATION WHERE 1 ORDER BY `length` ASC, CITY ASC LIMIT 1;

SELECT CITY, LENGTH(CITY) AS `length` FROM STATION WHERE 1 ORDER BY `length` DESC, CITY ASC LIMIT 1;